#!/bin/bash

cp -R $ANGL_PATH/autostart/install/* $ANGL_PATH/autostart

sed -i "s/[autostart_path]/$ANGL_PATH/g" $ANGL_PATH/autostart/autostart.service
sudo cp $ANGL_PATH/autostart/autostart.service /etc/systemd/system/
sudo systemctl enable autostart.service
